services:
  dynamodb:
    image: "amazon/dynamodb-local:2.4.0"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    healthcheck:
      test: [ "CMD-SHELL", "curl -v http://dynamodb:8000" ]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    ports:
      - "8000:8000"
  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin"
    ports:
      - "8001:8001"
    env_file:
      - ".env"
    depends_on:
      dynamodb:
        condition: service_healthy
  pricewatcher:
    image: serjayzem/pricewatcher
    env_file:
      - ".env"
    ports:
      - "3500:3500"
    depends_on:
      - dynamodb-admin