---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricewatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricewatcher
  template:
    metadata:
      labels:
        app: pricewatcher
    spec:
      containers:
      - name: pricewatcher
        image: serjayzem/pricewatcher:1.0.4
        ports:
        - containerPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  name: pricewatcher-service
spec:
  selector:
    app: pricewatcher
  ports:
  - protocol: TCP
    port: 80                
    targetPort: 3500
  type: LoadBalancer
